In [1]:
import pandas as pd
import pandera as pa

In [2]:
data = pd.read_csv("ocorrencia.csv", sep=";", parse_dates=['ocorrencia_dia'], dayfirst=True)
data = data.drop(['codigo_ocorrencia1', 'codigo_ocorrencia3','codigo_ocorrencia4', 'ocorrencia_latitude', 'ocorrencia_longitude', 
          'ocorrencia_pais', 'investigacao_aeronave_liberada','investigacao_status', 'divulgacao_relatorio_numero',
          'divulgacao_relatorio_publicado', 'divulgacao_dia_publicacao','total_aeronaves_envolvidas', 
          'ocorrencia_saida_pista'], axis=1)
data.head()

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
0,52242,52242,INCIDENTE,PORTO ALEGRE,RS,SBPA,2012-01-05,20:27:00,0
1,45331,45331,ACIDENTE,GUARULHOS,SP,SBGR,2012-01-06,13:44:00,3
2,45333,45333,ACIDENTE,VIAMÃO,RS,****,2012-01-06,13:00:00,0
3,45401,45401,ACIDENTE,SÃO SEBASTIÃO,SP,****,2012-01-06,17:00:00,0
4,45407,45407,ACIDENTE,SÃO SEPÉ,RS,****,2012-01-06,16:30:00,0

In [3]:
data.replace(['**','###!','####','****','*****','NULL'], pd.NA, inplace=True)

In [4]:
data

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
0,52242,52242,INCIDENTE,PORTO ALEGRE,RS,SBPA,2012-01-05,20:27:00,0
1,45331,45331,ACIDENTE,GUARULHOS,SP,SBGR,2012-01-06,13:44:00,3
2,45333,45333,ACIDENTE,VIAMÃO,RS,<NA>,2012-01-06,13:00:00,0
3,45401,45401,ACIDENTE,SÃO SEBASTIÃO,SP,<NA>,2012-01-06,17:00:00,0
4,45407,45407,ACIDENTE,SÃO SEPÉ,RS,<NA>,2012-01-06,16:30:00,0
...,...,...,...,...,...,...,...,...,...
5162,80458,80458,ACIDENTE,JATAÍ,GO,<NA>,2021-12-30,20:30:00,0
5163,80452,80452,ACIDENTE,MARACAÍ,SP,<NA>,2021-12-31,09:30:00,0
5164,80457,80457,INCIDENTE GRAVE,NOVO HAMBURGO,RS,SSNH,2021-12-31,11:59:00,0
5165,80460,80460,INCIDENTE,CURITIBA,PR,SBBI,2021-12-31,15:12:00,0
5166,80467,80467,INCIDENTE,PETROLINA,PE,SBPL,2021-12-31,20:30:00,0

In [5]:
schema = pa.DataFrameSchema(
    columns = {
        "codigo_ocorrencia": pa.Column(pa.Int),
        "codigo_ocorrencia2": pa.Column(pa.Int),
        "ocorrencia_classificacao": pa.Column(pa.String),
        "ocorrencia_cidade": pa.Column(pa.String),
        "ocorrencia_uf": pa.Column(pa.String, pa.Check.str_length(2,2), nullable=True),
        "ocorrencia_aerodromo": pa.Column(pa.String, nullable=True),
        "ocorrencia_dia": pa.Column(pa.DateTime),
        "ocorrencia_hora": pa.Column(pa.String, pa.Check.str_matches(r'^([0-1]?[0-9]|[2][0-3]):([0-5][0-9])(:[0-5][0-9])?$'), nullable=True),
        "total_recomendacoes": pa.Column(pa.Int)   
    }
)

In [6]:
schema.validate(data)

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
0,52242,52242,INCIDENTE,PORTO ALEGRE,RS,SBPA,2012-01-05,20:27:00,0
1,45331,45331,ACIDENTE,GUARULHOS,SP,SBGR,2012-01-06,13:44:00,3
2,45333,45333,ACIDENTE,VIAMÃO,RS,<NA>,2012-01-06,13:00:00,0
3,45401,45401,ACIDENTE,SÃO SEBASTIÃO,SP,<NA>,2012-01-06,17:00:00,0
4,45407,45407,ACIDENTE,SÃO SEPÉ,RS,<NA>,2012-01-06,16:30:00,0
...,...,...,...,...,...,...,...,...,...
5162,80458,80458,ACIDENTE,JATAÍ,GO,<NA>,2021-12-30,20:30:00,0
5163,80452,80452,ACIDENTE,MARACAÍ,SP,<NA>,2021-12-31,09:30:00,0
5164,80457,80457,INCIDENTE GRAVE,NOVO HAMBURGO,RS,SSNH,2021-12-31,11:59:00,0
5165,80460,80460,INCIDENTE,CURITIBA,PR,SBBI,2021-12-31,15:12:00,0
5166,80467,80467,INCIDENTE,PETROLINA,PE,SBPL,2021-12-31,20:30:00,0

In [7]:
data.dtypes

codigo_ocorrencia                    int64
codigo_ocorrencia2                   int64
ocorrencia_classificacao            object
ocorrencia_cidade                   object
ocorrencia_uf                       object
ocorrencia_aerodromo                object
ocorrencia_dia              datetime64[ns]
ocorrencia_hora                     object
total_recomendacoes                  int64
dtype: object

In [8]:
data.loc[1]

codigo_ocorrencia                         45331
codigo_ocorrencia2                        45331
ocorrencia_classificacao               ACIDENTE
ocorrencia_cidade                     GUARULHOS
ocorrencia_uf                                SP
ocorrencia_aerodromo                       SBGR
ocorrencia_dia              2012-01-06 00:00:00
ocorrencia_hora                        13:44:00
total_recomendacoes                           3
Name: 1, dtype: object

In [9]:
data.iloc[1]

codigo_ocorrencia                         45331
codigo_ocorrencia2                        45331
ocorrencia_classificacao               ACIDENTE
ocorrencia_cidade                     GUARULHOS
ocorrencia_uf                                SP
ocorrencia_aerodromo                       SBGR
ocorrencia_dia              2012-01-06 00:00:00
ocorrencia_hora                        13:44:00
total_recomendacoes                           3
Name: 1, dtype: object

In [10]:
data.iloc[-1]

codigo_ocorrencia                         80467
codigo_ocorrencia2                        80467
ocorrencia_classificacao              INCIDENTE
ocorrencia_cidade                     PETROLINA
ocorrencia_uf                                PE
ocorrencia_aerodromo                       SBPL
ocorrencia_dia              2021-12-31 00:00:00
ocorrencia_hora                        20:30:00
total_recomendacoes                           0
Name: 5166, dtype: object

In [11]:
data.tail()

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
5162,80458,80458,ACIDENTE,JATAÍ,GO,<NA>,2021-12-30,20:30:00,0
5163,80452,80452,ACIDENTE,MARACAÍ,SP,<NA>,2021-12-31,09:30:00,0
5164,80457,80457,INCIDENTE GRAVE,NOVO HAMBURGO,RS,SSNH,2021-12-31,11:59:00,0
5165,80460,80460,INCIDENTE,CURITIBA,PR,SBBI,2021-12-31,15:12:00,0
5166,80467,80467,INCIDENTE,PETROLINA,PE,SBPL,2021-12-31,20:30:00,0

In [12]:
data.loc[10:15]

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
10,45332,45332,ACIDENTE,VIAMÃO,RS,<NA>,2012-01-09,13:30:00,0
11,52245,52245,INCIDENTE,PORTO ALEGRE,RS,SBPA,2012-01-09,13:36:00,0
12,45396,45396,INCIDENTE GRAVE,MARABÁ,PA,SBMA,2012-01-11,11:21:00,0
13,45408,45408,ACIDENTE,ELDORADO,SP,<NA>,2012-01-11,13:45:00,1
14,45447,45447,INCIDENTE,RIO BRANCO,AC,<NA>,2012-01-13,18:15:00,0
15,45409,45409,ACIDENTE,CÁCERES,MT,<NA>,2012-01-14,10:00:00,0

In [13]:
data.loc[:,'ocorrencia_uf']

0       RS
1       SP
2       RS
3       SP
4       RS
        ..
5162    GO
5163    SP
5164    RS
5165    PR
5166    PE
Name: ocorrencia_uf, Length: 5167, dtype: object

In [14]:
data['ocorrencia_uf']

0       RS
1       SP
2       RS
3       SP
4       RS
        ..
5162    GO
5163    SP
5164    RS
5165    PR
5166    PE
Name: ocorrencia_uf, Length: 5167, dtype: object

In [15]:
data.isna().sum()

codigo_ocorrencia              0
codigo_ocorrencia2             0
ocorrencia_classificacao       0
ocorrencia_cidade              0
ocorrencia_uf                  2
ocorrencia_aerodromo        1905
ocorrencia_dia                 0
ocorrencia_hora                1
total_recomendacoes            0
dtype: int64

In [16]:
data.isnull().sum()

codigo_ocorrencia              0
codigo_ocorrencia2             0
ocorrencia_classificacao       0
ocorrencia_cidade              0
ocorrencia_uf                  2
ocorrencia_aerodromo        1905
ocorrencia_dia                 0
ocorrencia_hora                1
total_recomendacoes            0
dtype: int64

In [17]:
filtro = data.ocorrencia_uf.isnull()
data.loc[filtro]

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
1099,49474,49474,ACIDENTE,ÁGUAS INTERNACIONAIS,<NA>,<NA>,2013-09-02,02:54:00,0
4728,79956,79956,ACIDENTE,NÃO IDENTIFICADA,<NA>,<NA>,2021-02-26,11:00:00,0

In [18]:
filtro = data.ocorrencia_aerodromo.isnull()
data.loc[filtro]

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
2,45333,45333,ACIDENTE,VIAMÃO,RS,<NA>,2012-01-06,13:00:00,0
3,45401,45401,ACIDENTE,SÃO SEBASTIÃO,SP,<NA>,2012-01-06,17:00:00,0
4,45407,45407,ACIDENTE,SÃO SEPÉ,RS,<NA>,2012-01-06,16:30:00,0
5,52243,52243,INCIDENTE,UBATUBA,SP,<NA>,2012-01-06,14:30:00,0
8,45391,45391,ACIDENTE,CONCEIÇÃO DAS ALAGOAS,MG,<NA>,2012-01-08,16:00:00,0
...,...,...,...,...,...,...,...,...,...
5151,80446,80446,ACIDENTE,JACAREACANGA,PA,<NA>,2021-12-20,17:10:00,0
5155,80450,80450,ACIDENTE,DOURADOS,MS,<NA>,2021-12-28,10:30:00,0
5159,80455,80455,INCIDENTE GRAVE,SANTA RITA,PB,<NA>,2021-12-29,18:50:00,0
5162,80458,80458,ACIDENTE,JATAÍ,GO,<NA>,2021-12-30,20:30:00,0
5163,80452,80452,ACIDENTE,MARACAÍ,SP,<NA>,2021-12-31,09:30:00,0

In [19]:
filtro = data.ocorrencia_hora.isnull()
data.loc[filtro]

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
2974,78823,78823,INCIDENTE,CORUMBÁ,MS,<NA>,2017-07-09,NaN,0

In [20]:
data.count()

codigo_ocorrencia           5167
codigo_ocorrencia2          5167
ocorrencia_classificacao    5167
ocorrencia_cidade           5167
ocorrencia_uf               5165
ocorrencia_aerodromo        3262
ocorrencia_dia              5167
ocorrencia_hora             5166
total_recomendacoes         5167
dtype: int64

In [21]:
# ocorrências com mais de 10 recomendações
filtro = data.total_recomendacoes > 10
data.loc[filtro]

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
844,47938,47938,INCIDENTE,BRASÍLIA,DF,SBBR,2013-04-13,18:00:00,11
1669,52265,52265,ACIDENTE,SANTOS,SP,<NA>,2014-08-13,13:03:00,13
2804,66432,66432,INCIDENTE GRAVE,VITÓRIA,ES,<NA>,2017-02-21,11:47:00,12

In [22]:
# ocorrências com mais de 10 recomendações
filtro = data.total_recomendacoes > 10
data.loc[filtro, ['ocorrencia_cidade', 'total_recomendacoes']]

     ocorrencia_cidade  total_recomendacoes
844           BRASÍLIA                   11
1669            SANTOS                   13
2804           VITÓRIA                   12

In [23]:
# ocorrências cuja classificação == INCIDENTE GRAVE	
filtro = data.ocorrencia_classificacao == 'INCIDENTE GRAVE'
data.loc[filtro]

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
6,50713,50713,INCIDENTE GRAVE,CAMPINAS,SP,SDAI,2012-01-07,18:15:00,0
12,45396,45396,INCIDENTE GRAVE,MARABÁ,PA,SBMA,2012-01-11,11:21:00,0
18,50714,50714,INCIDENTE GRAVE,CAMOCIM,CE,SNWC,2012-01-17,18:25:00,0
19,45399,45399,INCIDENTE GRAVE,MUANÁ,PA,<NA>,2012-01-18,17:35:00,0
24,45582,45582,INCIDENTE GRAVE,RONDONÓPOLIS,MT,SWRD,2012-01-20,17:00:00,0
...,...,...,...,...,...,...,...,...,...
5139,80427,80427,INCIDENTE GRAVE,NOVA BANDEIRANTES,MT,<NA>,2021-12-12,17:20:00,0
5146,80448,80448,INCIDENTE GRAVE,FORMOSO DO ARAGUAIA,TO,<NA>,2021-12-18,19:00:00,0
5158,80454,80454,INCIDENTE GRAVE,ARAÇATUBA,SP,SBAU,2021-12-29,21:35:00,0
5159,80455,80455,INCIDENTE GRAVE,SANTA RITA,PB,<NA>,2021-12-29,18:50:00,0
5164,80457,80457,INCIDENTE GRAVE,NOVO HAMBURGO,RS,SSNH,2021-12-31,11:59:00,0

In [24]:
# ocorrências cuja classificação == INCIDENTE GRAVE e o estado == SP
filtro1 = data.ocorrencia_classificacao == 'INCIDENTE GRAVE'
filtro2 = data.ocorrencia_uf == 'SP'
data.loc[filtro1 & filtro2]

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
6,50713,50713,INCIDENTE GRAVE,CAMPINAS,SP,SDAI,2012-01-07,18:15:00,0
78,45598,45598,INCIDENTE GRAVE,BRAGANÇA PAULISTA,SP,SBBP,2012-02-20,14:10:00,0
86,45653,45653,INCIDENTE GRAVE,GUARULHOS,SP,SBGR,2012-02-24,20:04:00,0
91,45599,45599,INCIDENTE GRAVE,BRAGANÇA PAULISTA,SP,SBBP,2012-02-27,19:15:00,0
140,45651,45651,INCIDENTE GRAVE,ITU,SP,<NA>,2012-03-24,20:45:00,1
...,...,...,...,...,...,...,...,...,...
4954,80200,80200,INCIDENTE GRAVE,BRAGANÇA PAULISTA,SP,SDVH,2021-07-25,12:25:00,0
4980,80238,80238,INCIDENTE GRAVE,VOTUPORANGA,SP,SDVG,2021-08-11,19:09:00,0
5003,80265,80265,INCIDENTE GRAVE,SÃO PAULO,SP,SBMT,2021-08-31,16:50:00,0
5098,80382,80382,INCIDENTE GRAVE,PIRACICABA,SP,SDPW,2021-11-16,20:50:00,0
5158,80454,80454,INCIDENTE GRAVE,ARAÇATUBA,SP,SBAU,2021-12-29,21:35:00,0

In [25]:
# ocorrências cuja classificação == INCIDENTE GRAVE ou o estado == SP
filtro1 = data.ocorrencia_classificacao == 'INCIDENTE GRAVE'
filtro2 = data.ocorrencia_uf == 'SP'
data.loc[filtro1 | filtro2]

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
1,45331,45331,ACIDENTE,GUARULHOS,SP,SBGR,2012-01-06,13:44:00,3
3,45401,45401,ACIDENTE,SÃO SEBASTIÃO,SP,<NA>,2012-01-06,17:00:00,0
5,52243,52243,INCIDENTE,UBATUBA,SP,<NA>,2012-01-06,14:30:00,0
6,50713,50713,INCIDENTE GRAVE,CAMPINAS,SP,SDAI,2012-01-07,18:15:00,0
12,45396,45396,INCIDENTE GRAVE,MARABÁ,PA,SBMA,2012-01-11,11:21:00,0
...,...,...,...,...,...,...,...,...,...
5158,80454,80454,INCIDENTE GRAVE,ARAÇATUBA,SP,SBAU,2021-12-29,21:35:00,0
5159,80455,80455,INCIDENTE GRAVE,SANTA RITA,PB,<NA>,2021-12-29,18:50:00,0
5161,80456,80456,INCIDENTE,SÃO PAULO,SP,SBSP,2021-12-30,13:15:00,0
5163,80452,80452,ACIDENTE,MARACAÍ,SP,<NA>,2021-12-31,09:30:00,0
5164,80457,80457,INCIDENTE GRAVE,NOVO HAMBURGO,RS,SSNH,2021-12-31,11:59:00,0

In [26]:
# ocorrências cuja (classificação == INCIDENTE GRAVE ou classificação == INCIDENTE) e o estado == SP
filtro1 = data.ocorrencia_classificacao.isin(['INCIDENTE GRAVE', 'INCIDENTE'])
filtro2 = data.ocorrencia_uf == 'SP'
data.loc[filtro1 & filtro2]

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
5,52243,52243,INCIDENTE,UBATUBA,SP,<NA>,2012-01-06,14:30:00,0
6,50713,50713,INCIDENTE GRAVE,CAMPINAS,SP,SDAI,2012-01-07,18:15:00,0
28,52248,52248,INCIDENTE,SÃO PAULO,SP,SBMT,2012-01-21,11:15:00,0
35,52054,52054,INCIDENTE,SÃO PAULO,SP,SBMT,2012-01-25,23:00:00,0
36,52055,52055,INCIDENTE,RIBEIRÃO PRETO,SP,<NA>,2012-01-25,09:30:00,0
...,...,...,...,...,...,...,...,...,...
5134,80425,80425,INCIDENTE,SÃO PAULO,SP,SBSP,2021-12-09,20:30:00,0
5143,80431,80431,INCIDENTE,SANTOS,SP,SBST,2021-12-15,12:30:00,0
5157,80453,80453,INCIDENTE,CAMPINAS,SP,SBKP,2021-12-29,09:00:00,0
5158,80454,80454,INCIDENTE GRAVE,ARAÇATUBA,SP,SBAU,2021-12-29,21:35:00,0
5161,80456,80456,INCIDENTE,SÃO PAULO,SP,SBSP,2021-12-30,13:15:00,0

In [27]:
# ocorrências cuja cidade comecem com a letra C
filtro = data.ocorrencia_cidade.str[0] == 'C'
data.loc[filtro]

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
6,50713,50713,INCIDENTE GRAVE,CAMPINAS,SP,SDAI,2012-01-07,18:15:00,0
8,45391,45391,ACIDENTE,CONCEIÇÃO DAS ALAGOAS,MG,<NA>,2012-01-08,16:00:00,0
15,45409,45409,ACIDENTE,CÁCERES,MT,<NA>,2012-01-14,10:00:00,0
18,50714,50714,INCIDENTE GRAVE,CAMOCIM,CE,SNWC,2012-01-17,18:25:00,0
22,45390,45390,ACIDENTE,CACHOEIRA DOURADA,GO,<NA>,2012-01-20,21:00:00,0
...,...,...,...,...,...,...,...,...,...
5142,80434,80434,ACIDENTE,CARACOL,MS,<NA>,2021-12-14,21:35:00,0
5144,80447,80447,INCIDENTE,CONFINS,MG,SBCF,2021-12-15,17:10:00,0
5150,80445,80445,ACIDENTE,CHUPINGUAIA,RO,<NA>,2021-12-20,12:05:00,0
5157,80453,80453,INCIDENTE,CAMPINAS,SP,SBKP,2021-12-29,09:00:00,0
5165,80460,80460,INCIDENTE,CURITIBA,PR,SBBI,2021-12-31,15:12:00,0

In [28]:
# ocorrências cuja cidade terminam com a letra A
filtro = data.ocorrencia_cidade.str[-1] == 'A'
data.loc[filtro]

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
5,52243,52243,INCIDENTE,UBATUBA,SP,<NA>,2012-01-06,14:30:00,0
9,52244,52244,INCIDENTE,UBERLÂNDIA,MG,SBUL,2012-01-08,22:13:00,0
17,52246,52246,INCIDENTE,BRASÍLIA,DF,SBBR,2012-01-16,16:47:00,0
21,45392,45392,ACIDENTE,BRASÍLIA,DF,<NA>,2012-01-19,21:30:00,2
22,45390,45390,ACIDENTE,CACHOEIRA DOURADA,GO,<NA>,2012-01-20,21:00:00,0
...,...,...,...,...,...,...,...,...,...
5152,80465,80465,INCIDENTE,VITÓRIA,ES,SBVT,2021-12-21,22:25:00,0
5158,80454,80454,INCIDENTE GRAVE,ARAÇATUBA,SP,SBAU,2021-12-29,21:35:00,0
5159,80455,80455,INCIDENTE GRAVE,SANTA RITA,PB,<NA>,2021-12-29,18:50:00,0
5165,80460,80460,INCIDENTE,CURITIBA,PR,SBBI,2021-12-31,15:12:00,0
5166,80467,80467,INCIDENTE,PETROLINA,PE,SBPL,2021-12-31,20:30:00,0

In [29]:
# ocorrências cuja cidade terminam com os caracteres MA
filtro = data.ocorrencia_cidade.str[-2:] == 'MA'
data.loc[filtro]

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
249,45939,45939,ACIDENTE,UMUARAMA,PR,<NA>,2012-05-30,19:00:00,0
273,46180,46180,ACIDENTE,AURIFLAMA,SP,<NA>,2012-06-16,19:30:00,0
971,49113,49113,INCIDENTE GRAVE,NOVA LIMA,MG,<NA>,2013-06-15,12:00:00,4
974,48799,48799,ACIDENTE,CANUTAMA,AM,<NA>,2013-06-18,21:30:00,0
1518,80059,80059,INCIDENTE,IVINHEMA,MS,<NA>,2014-04-27,11:30:00,0
1529,51347,51347,INCIDENTE,DIADEMA,SP,<NA>,2014-05-04,16:00:00,0
1729,52340,52340,ACIDENTE,FAMA,MG,<NA>,2014-09-20,15:00:00,1
1840,52832,52832,ACIDENTE,BURITAMA,SP,<NA>,2014-12-14,23:40:00,0
1871,52979,52979,ACIDENTE,IVINHEMA,MS,<NA>,2015-01-02,14:50:00,0
1914,52984,52984,ACIDENTE,NOVA LIMA,MG,SJLY,2015-02-01,15:10:00,0
1966,53596,53596,INCIDENTE,ITAPEMA,SC,<NA>,2015-03-10,21:35:00,0
2031,53223,53223,ACIDENTE,PINDORAMA,SP,<NA>,2015-04-22,12:45:00,0
2045,53265,53265,ACIDENTE,PACARAIMA,RR,SDMM,2015-05-05,16:05:00,2
2063,53271,53271,INCIDENTE GRAVE,UMUARAMA,PR,<NA>,2015-05-17,17:00:00,0
2556,65414,65414,INCIDENTE GRAVE,NOVA LIMA,MG,SJLY,2016-07-08,19:50:00,1
2599,65633,65633,INCIDENTE GRAVE,NOVA LIMA,MG,<NA>,2016-08-31,17:40:00,0
2755,66265,66265,ACIDENTE,BURITAMA,SP,<NA>,2017-01-13,16:00:00,0
3104,77371,77371,ACIDENTE,CANUTAMA,AM,SDKH,2017-11-02,19:30:00,1
3186,77612,77612,ACIDENTE,ITAPEMA,SC,<NA>,2018-01-06,10:30:00,0
3449,78080,78080,ACIDENTE,ITAPEMA,SC,<NA>,2018-07-28,14:20:00,0
3861,78867,78867,INCIDENTE,IRACEMA,RR,<NA>,2019-07-06,00:00:00,0
3945,78923,78923,INCIDENTE GRAVE,CANUTAMA,AM,<NA>,2019-09-03,14:00:00,0
3955,78782,78782,ACIDENTE,IVINHEMA,MS,<NA>,2019-09-08,17:45:00,0
4279,79282,79282,ACIDENTE,ITURAMA,MG,<NA>,2020-04-11,12:20:00,0
4314,79338,79338,INCIDENTE,IVINHEMA,MS,<NA>,2020-05-15,09:40:00,0
4348,79400,79400,INCIDENTE,IBIRAMA,SC,<NA>,2020-06-09,14:00:00,0
4632,79823,79823,ACIDENTE,IRACEMA,RR,<NA>,2021-01-05,20:07:00,0
4649,79820,79820,INCIDENTE,NOVA LIMA,MG,SJLY,2021-01-14,09:27:00,0
4651,79830,79830,INCIDENTE,NOVA LIMA,MG,SJLY,2021-01-14,09:27:00,0
4734,79943,79943,INCIDENTE,IBOTIRAMA,BA,SNIT,2021-03-03,11:30:00,0
4967,80227,80227,ACIDENTE,UMUARAMA,PR,<NA>,2021-08-02,14:30:00,0
4969,80252,80252,ACIDENTE,IRACEMA,RR,<NA>,2021-08-04,11:45:00,0

In [30]:
# ocorrências cuja cidade contém (em qualquer parte do conteúdo) os caracteres MA ou AL
filtro = data.ocorrencia_cidade.str.contains('MA|AL')
data.loc[filtro]

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
0,52242,52242,INCIDENTE,PORTO ALEGRE,RS,SBPA,2012-01-05,20:27:00,0
8,45391,45391,ACIDENTE,CONCEIÇÃO DAS ALAGOAS,MG,<NA>,2012-01-08,16:00:00,0
11,52245,52245,INCIDENTE,PORTO ALEGRE,RS,SBPA,2012-01-09,13:36:00,0
12,45396,45396,INCIDENTE GRAVE,MARABÁ,PA,SBMA,2012-01-11,11:21:00,0
16,45693,45693,INCIDENTE,MACAÉ,RJ,<NA>,2012-01-14,10:30:00,0
...,...,...,...,...,...,...,...,...,...
5153,80461,80461,INCIDENTE,MARINGÁ,PR,SBMG,2021-12-24,03:30:00,0
5154,80468,80468,INCIDENTE,SALVADOR,BA,SBSV,2021-12-26,16:56:00,0
5156,80463,80463,INCIDENTE,MARINGÁ,PR,SBMG,2021-12-28,16:11:00,0
5160,80451,80451,INCIDENTE,MANAUS,AM,SBEG,2021-12-30,14:41:00,0
5163,80452,80452,ACIDENTE,MARACAÍ,SP,<NA>,2021-12-31,09:30:00,0

In [31]:
# ocorrências do ano de 2015
filtro = data.ocorrencia_dia.dt.year == 2015
data.loc[filtro]

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
1870,52992,52992,INCIDENTE GRAVE,SALVADOR,BA,SBSV,2015-01-01,11:40:00,3
1871,52979,52979,ACIDENTE,IVINHEMA,MS,<NA>,2015-01-02,14:50:00,0
1872,53073,53073,INCIDENTE,TEFÉ,AM,SBTF,2015-01-02,16:28:00,0
1873,53074,53074,INCIDENTE,BELO HORIZONTE,MG,SBBH,2015-01-02,20:34:00,0
1874,52976,52976,ACIDENTE,TOLEDO,PR,SBTD,2015-01-04,22:04:00,6
...,...,...,...,...,...,...,...,...,...
2336,60632,60632,INCIDENTE GRAVE,ITABERÁ,SP,<NA>,2015-12-24,14:00:00,0
2337,60600,60600,INCIDENTE,GUARULHOS,SP,SBGR,2015-12-25,19:00:00,0
2338,60642,60642,INCIDENTE,SÃO FRANCISCO DO SUL,SC,SSSS,2015-12-26,16:00:00,0
2339,60631,60631,ACIDENTE,MAÇAMBARÁ,RS,<NA>,2015-12-28,19:00:00,2
2340,60649,60649,ACIDENTE,PORTO BELO,SC,SDEN,2015-12-31,14:00:00,0

In [32]:
data.dtypes

codigo_ocorrencia                    int64
codigo_ocorrencia2                   int64
ocorrencia_classificacao            object
ocorrencia_cidade                   object
ocorrencia_uf                       object
ocorrencia_aerodromo                object
ocorrencia_dia              datetime64[ns]
ocorrencia_hora                     object
total_recomendacoes                  int64
dtype: object

In [36]:
#ocorrências do ano de 2015 e mês 12 e dias entre 3 e 8
filtro_ano = data.ocorrencia_dia.dt.year == 2015
filtro_mes = data.ocorrencia_dia.dt.month == 12
filtro_dia_inicio = data.ocorrencia_dia.dt.day > 2 
filtro_dia_fim = data.ocorrencia_dia.dt.day < 9
data.loc[filtro_ano & filtro_mes & filtro_dia_inicio & filtro_dia_fim]

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes
2306,53575,53575,INCIDENTE,CAMPOS DOS GOYTACAZES,RJ,SBFS,2015-12-03,10:50:00,0
2307,60637,60637,INCIDENTE,BELO HORIZONTE,MG,SBBH,2015-12-03,16:47:00,0
2308,53625,53625,ACIDENTE,TRINDADE,GO,<NA>,2015-12-06,13:10:00,3
2309,53626,53626,ACIDENTE,AMERICANA,SP,SDAI,2015-12-06,15:00:00,1
2310,53628,53628,ACIDENTE,AGUAÍ,SP,<NA>,2015-12-08,14:30:00,1
2311,53629,53629,INCIDENTE GRAVE,JALES,SP,SDJL,2015-12-08,10:20:00,0
2312,53631,53631,INCIDENTE,CAMPINAS,SP,SBKP,2015-12-08,16:19:00,0
2313,60636,60636,INCIDENTE,CAXIAS DO SUL,RS,SBCX,2015-12-08,13:00:00,0

In [38]:
data['ocorrencia_dia_hora'] = pd.to_datetime(data.ocorrencia_dia.astype(str) + ' '  + data.ocorrencia_hora)

In [39]:
data.head()

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes,ocorrencia_dia_hora
0,52242,52242,INCIDENTE,PORTO ALEGRE,RS,SBPA,2012-01-05,20:27:00,0,2012-01-05 20:27:00
1,45331,45331,ACIDENTE,GUARULHOS,SP,SBGR,2012-01-06,13:44:00,3,2012-01-06 13:44:00
2,45333,45333,ACIDENTE,VIAMÃO,RS,<NA>,2012-01-06,13:00:00,0,2012-01-06 13:00:00
3,45401,45401,ACIDENTE,SÃO SEBASTIÃO,SP,<NA>,2012-01-06,17:00:00,0,2012-01-06 17:00:00
4,45407,45407,ACIDENTE,SÃO SEPÉ,RS,<NA>,2012-01-06,16:30:00,0,2012-01-06 16:30:00

In [40]:
filtro1 = data.ocorrencia_dia_hora >= '2015-12-03 11:00:00'
filtro2 = data.ocorrencia_dia_hora <= '2015-12-08 14:30:00'
data.loc[filtro1 & filtro2]

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes,ocorrencia_dia_hora
2307,60637,60637,INCIDENTE,BELO HORIZONTE,MG,SBBH,2015-12-03,16:47:00,0,2015-12-03 16:47:00
2308,53625,53625,ACIDENTE,TRINDADE,GO,<NA>,2015-12-06,13:10:00,3,2015-12-06 13:10:00
2309,53626,53626,ACIDENTE,AMERICANA,SP,SDAI,2015-12-06,15:00:00,1,2015-12-06 15:00:00
2310,53628,53628,ACIDENTE,AGUAÍ,SP,<NA>,2015-12-08,14:30:00,1,2015-12-08 14:30:00
2311,53629,53629,INCIDENTE GRAVE,JALES,SP,SDJL,2015-12-08,10:20:00,0,2015-12-08 10:20:00
2313,60636,60636,INCIDENTE,CAXIAS DO SUL,RS,SBCX,2015-12-08,13:00:00,0,2015-12-08 13:00:00

In [41]:
# ocorrências do ano de 2015 e mês 03
filtro1 = data.ocorrencia_dia.dt.year == 2015
filtro2 = data.ocorrencia_dia.dt.month == 3
df201503 = data.loc[filtro1 & filtro2]
df201503

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes,ocorrencia_dia_hora
1960,53183,53183,ACIDENTE,AMAPORÃ,PR,<NA>,2015-03-02,23:00:00,0,2015-03-02 23:00:00
1961,53120,53120,ACIDENTE,CHAVES,PA,SNXW,2015-03-04,13:30:00,0,2015-03-04 13:30:00
1962,53109,53109,ACIDENTE,CAMPO GRANDE,MS,SSIE,2015-03-05,13:50:00,0,2015-03-05 13:50:00
1963,53112,53112,ACIDENTE,MOGI GUAÇU,SP,<NA>,2015-03-06,21:00:00,1,2015-03-06 21:00:00
1964,53152,53152,INCIDENTE GRAVE,RIO DE JANEIRO,RJ,SBRJ,2015-03-10,11:30:00,2,2015-03-10 11:30:00
1965,53167,53167,INCIDENTE,MARABÁ,PA,SBMA,2015-03-10,17:33:00,0,2015-03-10 17:33:00
1966,53596,53596,INCIDENTE,ITAPEMA,SC,<NA>,2015-03-10,21:35:00,0,2015-03-10 21:35:00
1967,53149,53149,ACIDENTE,TABATINGA,AM,SBTT,2015-03-11,23:25:00,0,2015-03-11 23:25:00
1968,53148,53148,ACIDENTE,ARARAS,SP,SDEH,2015-03-12,12:40:00,0,2015-03-12 12:40:00
1969,53153,53153,INCIDENTE,PORTO ALEGRE,RS,SBPA,2015-03-13,15:45:00,0,2015-03-13 15:45:00
1970,53154,53154,INCIDENTE,SOROCABA,SP,SDCO,2015-03-13,14:40:00,0,2015-03-13 14:40:00
1971,53238,53238,INCIDENTE,SERRA,ES,<NA>,2015-03-13,11:30:00,0,2015-03-13 11:30:00
1972,53189,53189,INCIDENTE,CONFINS,MG,SBCF,2015-03-14,07:20:00,0,2015-03-14 07:20:00
1973,53193,53193,ACIDENTE,CANARANA,MT,<NA>,2015-03-14,18:00:00,0,2015-03-14 18:00:00
1974,53164,53164,ACIDENTE,PRINCESA ISABEL,PB,<NA>,2015-03-15,18:30:00,0,2015-03-15 18:30:00
1975,53151,53151,INCIDENTE GRAVE,MAUÉS,AM,SWMW,2015-03-16,18:07:00,1,2015-03-16 18:07:00
1976,53168,53168,INCIDENTE,PARÁ DE MINAS,MG,SNPA,2015-03-16,21:05:00,0,2015-03-16 21:05:00
1977,53169,53169,INCIDENTE,BELÉM,PA,SBBE,2015-03-19,03:25:00,0,2015-03-19 03:25:00
1978,53165,53165,INCIDENTE GRAVE,SÃO DESIDÉRIO,BA,<NA>,2015-03-20,14:35:00,0,2015-03-20 14:35:00
1979,53188,53188,INCIDENTE,RIO DE JANEIRO,RJ,SBJR,2015-03-20,21:00:00,0,2015-03-20 21:00:00
1980,53184,53184,ACIDENTE,PORTO UNIÃO,SC,<NA>,2015-03-22,13:44:00,0,2015-03-22 13:44:00
1981,53178,53178,ACIDENTE,DIAMANTINO,MT,<NA>,2015-03-23,17:15:00,0,2015-03-23 17:15:00
1982,53182,53182,ACIDENTE,SANTA LUZIA,MA,<NA>,2015-03-23,20:40:00,0,2015-03-23 20:40:00
1983,53166,53166,INCIDENTE GRAVE,RIACHÃO DAS NEVES,BA,<NA>,2015-03-24,14:45:00,0,2015-03-24 14:45:00
1984,53170,53170,INCIDENTE,CONFINS,MG,SBCF,2015-03-24,17:57:00,0,2015-03-24 17:57:00
1985,53185,53185,INCIDENTE,CURITIBA,PR,SBCT,2015-03-24,23:01:00,0,2015-03-24 23:01:00
1986,53412,53412,INCIDENTE GRAVE,MACAÉ,RJ,<NA>,2015-03-24,16:35:00,0,2015-03-24 16:35:00
1987,53194,53194,ACIDENTE,GUARACIABA DO NORTE,CE,SWBE,2015-03-26,20:30:00,0,2015-03-26 20:30:00
1988,53186,53186,INCIDENTE,BRASÍLIA,DF,<NA>,2015-03-27,14:55:00,0,2015-03-27 14:55:00
1989,53179,53179,ACIDENTE,CAIAPÔNIA,GO,<NA>,2015-03-28,10:30:00,0,2015-03-28 10:30:00
1990,53180,53180,ACIDENTE,ARAGUARI,MG,<NA>,2015-03-28,18:52:00,0,2015-03-28 18:52:00
1991,53190,53190,INCIDENTE,CAMPINAS,SP,SBKP,2015-03-28,16:26:00,0,2015-03-28 16:26:00
1992,53212,53212,INCIDENTE,JUNDIAÍ,SP,SBJD,2015-03-28,17:32:00,0,2015-03-28 17:32:00
1993,53213,53213,INCIDENTE,JUNDIAÍ,SP,SBJD,2015-03-28,15:51:00,0,2015-03-28 15:51:00
1994,53181,53181,ACIDENTE,COLÍDER,MT,<NA>,2015-03-29,20:17:00,0,2015-03-29 20:17:00
1995,53187,53187,INCIDENTE,JOINVILLE,SC,SBJV,2015-03-29,18:36:00,0,2015-03-29 18:36:00
1996,53211,53211,INCIDENTE,BAURU,SP,SBBU,2015-03-30,19:40:00,0,2015-03-30 19:40:00

In [42]:
df201503.count()

codigo_ocorrencia           37
codigo_ocorrencia2          37
ocorrencia_classificacao    37
ocorrencia_cidade           37
ocorrencia_uf               37
ocorrencia_aerodromo        21
ocorrencia_dia              37
ocorrencia_hora             37
total_recomendacoes         37
ocorrencia_dia_hora         37
dtype: int64

In [43]:
df201503.groupby(['ocorrencia_classificacao']).codigo_ocorrencia.count()

ocorrencia_classificacao
ACIDENTE           15
INCIDENTE          17
INCIDENTE GRAVE     5
Name: codigo_ocorrencia, dtype: int64

In [44]:
df201503.groupby(['ocorrencia_classificacao']).ocorrencia_aerodromo.count()

ocorrencia_classificacao
ACIDENTE            5
INCIDENTE          14
INCIDENTE GRAVE     2
Name: ocorrencia_aerodromo, dtype: int64

In [45]:
df201503.groupby(['ocorrencia_classificacao']).size()

ocorrencia_classificacao
ACIDENTE           15
INCIDENTE          17
INCIDENTE GRAVE     5
dtype: int64

In [46]:
df201503.groupby(['ocorrencia_classificacao']).size().sort_values()

ocorrencia_classificacao
INCIDENTE GRAVE     5
ACIDENTE           15
INCIDENTE          17
dtype: int64

In [47]:
df201503.groupby(['ocorrencia_classificacao']).size().sort_values(ascending=False)

ocorrencia_classificacao
INCIDENTE          17
ACIDENTE           15
INCIDENTE GRAVE     5
dtype: int64

In [56]:
filtro1 = data.ocorrencia_dia.dt.year == 2012
filtro2 = data.ocorrencia_uf.isin(['PR','SC','RS'])
dfsul2012 = data.loc[filtro1 & filtro2]
dfsul2012

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes,ocorrencia_dia_hora
0,52242,52242,INCIDENTE,PORTO ALEGRE,RS,SBPA,2012-01-05,20:27:00,0,2012-01-05 20:27:00
2,45333,45333,ACIDENTE,VIAMÃO,RS,<NA>,2012-01-06,13:00:00,0,2012-01-06 13:00:00
4,45407,45407,ACIDENTE,SÃO SEPÉ,RS,<NA>,2012-01-06,16:30:00,0,2012-01-06 16:30:00
10,45332,45332,ACIDENTE,VIAMÃO,RS,<NA>,2012-01-09,13:30:00,0,2012-01-09 13:30:00
11,52245,52245,INCIDENTE,PORTO ALEGRE,RS,SBPA,2012-01-09,13:36:00,0,2012-01-09 13:36:00
...,...,...,...,...,...,...,...,...,...,...
607,46752,46752,ACIDENTE,SANTA VITÓRIA DO PALMAR,RS,<NA>,2012-12-10,10:30:00,1,2012-12-10 10:30:00
609,46789,46789,INCIDENTE,PORTO ALEGRE,RS,SBPA,2012-12-10,19:45:00,0,2012-12-10 19:45:00
615,46751,46751,ACIDENTE,URUGUAIANA,RS,SJDU,2012-12-13,22:00:00,2,2012-12-13 22:00:00
621,46823,46823,INCIDENTE GRAVE,ROSÁRIO DO SUL,RS,SSRZ,2012-12-16,22:30:00,1,2012-12-16 22:30:00
635,46792,46792,INCIDENTE,PORTO ALEGRE,RS,SBPA,2012-12-26,21:40:00,0,2012-12-26 21:40:00

In [57]:
dfsul2012.groupby(['ocorrencia_classificacao']).size()

ocorrencia_classificacao
ACIDENTE           34
INCIDENTE          44
INCIDENTE GRAVE    15
dtype: int64

In [58]:
dfsul2012.count()

codigo_ocorrencia           93
codigo_ocorrencia2          93
ocorrencia_classificacao    93
ocorrencia_cidade           93
ocorrencia_uf               93
ocorrencia_aerodromo        59
ocorrencia_dia              93
ocorrencia_hora             93
total_recomendacoes         93
ocorrencia_dia_hora         93
dtype: int64

In [59]:
dfsul2012.groupby(['ocorrencia_uf', 'ocorrencia_classificacao']).size()

ocorrencia_uf  ocorrencia_classificacao
PR             ACIDENTE                    14
               INCIDENTE                   23
               INCIDENTE GRAVE              6
RS             ACIDENTE                    13
               INCIDENTE                   18
               INCIDENTE GRAVE              6
SC             ACIDENTE                     7
               INCIDENTE                    3
               INCIDENTE GRAVE              3
dtype: int64

In [60]:
dfsul2012.groupby(['ocorrencia_cidade']).size().sort_values(ascending=False)

ocorrencia_cidade
PORTO ALEGRE               14
LONDRINA                   12
CURITIBA                    9
CASCAVEL                    4
MARINGÁ                     3
PELOTAS                     3
VIAMÃO                      2
NAVEGANTES                  2
LUIZ ALVES                  2
FOZ DO IGUAÇU               2
SANTA MARIA                 2
OSÓRIO                      2
SÃO JOSÉ                    2
SÃO JOSÉ DOS PINHAIS        2
SÃO SEPÉ                    2
SANTA VITÓRIA DO PALMAR     1
SANTO ÂNGELO                1
SÃO BORJA                   1
ROSÁRIO DO SUL              1
RIO GRANDE                  1
QUERÊNCIA DO NORTE          1
TOLEDO                      1
PONTA GROSSA                1
UMUARAMA                    1
URUGUAIANA                  1
SANTA MARIANA               1
ALEGRETE                    1
PALMEIRA                    1
ALMIRANTE TAMANDARÉ         1
ALTÔNIA                     1
ARROIO GRANDE               1
BAGÉ                        1
BALNEÁRIO CAMBORIÚ          1
BELA VISTA DO PARAÍSO       1
BLUMENAU                    1
CAMPINA GRANDE DO SUL       1
CHAPECÓ                     1
CORUPÁ                      1
ESPUMOSO                    1
FLORIANÓPOLIS               1
GUAÍBA                      1
IMBITUBA                    1
ITAQUI                      1
JOINVILLE                   1
MARECHAL CÂNDIDO RONDON     1
dtype: int64

In [67]:
filtro1 = dfsul2012.ocorrencia_cidade == 'URUGUAIANA'
filtro2 = dfsul2012.total_recomendacoes > 0
dfsul2012.loc[filtro1 & filtro2]

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes,ocorrencia_dia_hora
615,46751,46751,ACIDENTE,URUGUAIANA,RS,SJDU,2012-12-13,22:00:00,2,2012-12-13 22:00:00

In [69]:
filtro = dfsul2012.ocorrencia_cidade == 'URUGUAIANA'
dfsul2012.loc[filtro].total_recomendacoes.sum()

2

In [70]:
dfsul2012.groupby(['ocorrencia_aerodromo'], dropna=False).total_recomendacoes.sum()

ocorrencia_aerodromo
SBBI     0
SBCA     1
SBCT     0
SBFI     0
SBFL     0
SBJV     0
SBLO     0
SBMG     0
SBNF     0
SBNM     0
SBPA     0
SBPG     0
SBPK     0
SBTD     0
SIBK     1
SJDU     2
SSBL     0
SSBN     0
SSCR     2
SSHS     2
SSKT     0
SSOK     0
SSOS     0
SSRZ     1
SSSB     0
SSXO     0
NaN     14
Name: total_recomendacoes, dtype: int64

In [71]:
dfsul2012.groupby(['ocorrencia_cidade']).total_recomendacoes.sum()

ocorrencia_cidade
ALEGRETE                   0
ALMIRANTE TAMANDARÉ        9
ALTÔNIA                    0
ARROIO GRANDE              0
BAGÉ                       1
BALNEÁRIO CAMBORIÚ         0
BELA VISTA DO PARAÍSO      0
BLUMENAU                   0
CAMPINA GRANDE DO SUL      0
CASCAVEL                   1
CHAPECÓ                    0
CORUPÁ                     0
CURITIBA                   0
ESPUMOSO                   0
FLORIANÓPOLIS              0
FOZ DO IGUAÇU              2
GUAÍBA                     0
IMBITUBA                   0
ITAQUI                     0
JOINVILLE                  0
LONDRINA                   0
LUIZ ALVES                 1
MARECHAL CÂNDIDO RONDON    2
MARINGÁ                    0
NAVEGANTES                 0
OSÓRIO                     0
PALMEIRA                   3
PELOTAS                    0
PONTA GROSSA               0
PORTO ALEGRE               0
QUERÊNCIA DO NORTE         0
RIO GRANDE                 0
ROSÁRIO DO SUL             1
SANTA MARIA                0
SANTA MARIANA              0
SANTA VITÓRIA DO PALMAR    1
SANTO ÂNGELO               0
SÃO BORJA                  0
SÃO JOSÉ                   0
SÃO JOSÉ DOS PINHAIS       0
SÃO SEPÉ                   0
TOLEDO                     0
UMUARAMA                   0
URUGUAIANA                 2
VIAMÃO                     0
Name: total_recomendacoes, dtype: int64

In [73]:
filtro = dfsul2012.total_recomendacoes > 0
dfsul2012.loc[filtro].groupby(['ocorrencia_cidade']).total_recomendacoes.sum().sort_values()

ocorrencia_cidade
BAGÉ                       1
CASCAVEL                   1
LUIZ ALVES                 1
ROSÁRIO DO SUL             1
SANTA VITÓRIA DO PALMAR    1
FOZ DO IGUAÇU              2
MARECHAL CÂNDIDO RONDON    2
URUGUAIANA                 2
PALMEIRA                   3
ALMIRANTE TAMANDARÉ        9
Name: total_recomendacoes, dtype: int64

In [75]:
dfsul2012.loc[filtro].groupby(['ocorrencia_cidade', dfsul2012.ocorrencia_dia.dt.month]).total_recomendacoes.sum()

ocorrencia_cidade        ocorrencia_dia
ALMIRANTE TAMANDARÉ      11                9
BAGÉ                     11                1
CASCAVEL                 9                 1
FOZ DO IGUAÇU            9                 2
LUIZ ALVES               3                 1
MARECHAL CÂNDIDO RONDON  5                 2
PALMEIRA                 8                 3
ROSÁRIO DO SUL           12                1
SANTA VITÓRIA DO PALMAR  12                1
URUGUAIANA               12                2
Name: total_recomendacoes, dtype: int64

In [78]:
filtro1 = dfsul2012.total_recomendacoes > 0
filtro2 = dfsul2012.ocorrencia_cidade == 'ROSÁRIO DO SUL'
dfsul2012.loc[filtro1 & filtro2]

,codigo_ocorrencia,codigo_ocorrencia2,ocorrencia_classificacao,ocorrencia_cidade,ocorrencia_uf,ocorrencia_aerodromo,ocorrencia_dia,ocorrencia_hora,total_recomendacoes,ocorrencia_dia_hora
621,46823,46823,INCIDENTE GRAVE,ROSÁRIO DO SUL,RS,SSRZ,2012-12-16,22:30:00,1,2012-12-16 22:30:00